[package]
name = "statisk"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.3"
anyhow = "1.0.72"
axum = { version = "0.6.20", features = ["ws"] }
brotli = "3.3.4"
flate2 = "1.0.26"
grass = { version = "0.13.1", default-features = false }
jiff = { version = "0.1.29", features = ["serde"] }
jotdown = "0.3.0"
lightningcss = { version = "1.0.0-alpha.44", default-features = false, features = ["browserslist", "grid"] }
minijinja = { version = "1.0.5", features = ["loader", "speedups"] }
minijinja-autoreload = "1.0.5"
notify = "6.1.1"
serde = { version = "1.0.176", features = ["derive"] }
sha1_smol = { version = "1.0.0", features = ["std"] }
swc_common = "6.0.0"
swc_html_codegen = "6.0.0"
swc_html_minifier = "10.0.0"
swc_html_parser = "6.0.0"
time = { version = "0.3.37", features = ["serde-human-readable", "local-offset"] }
tokio = { version = "1.32.0", features = ["full"] }
toml = "0.8.19"
tower-http = { version = "0.4.4", features = ["fs", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "time"] }
url = { version = "2.4.0", features = ["serde"] }
walkdir = "2.3.3"
xml-rs = "0.8.25"

[dev-dependencies]
insta = { version = "1.42.1", features = ["toml"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
